"""Add spec_id to comments

Revision ID: 646b92e86c27
Revises: a4e8065c8b5c
Create Date: 2025-07-03 23:03:24.396653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '646b92e86c27'
down_revision: Union[str, Sequence[str], None] = 'a4e8065c8b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('spec_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'specs', ['spec_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'spec_id')
    # ### end Alembic commands ###
